FROM python:3.10
MAINTAINER John Luo
 
# Creating Application Source Code Directory
RUN mkdir -p /pymilvus/src

# Setting Home Directory for containers
WORKDIR /pymilvus/src

RUN pip install pymilvus==2.0.2
